Update error check

diff --git a/bin/create-c-app b/bin/create-c-app
--- a/bin/create-c-app
+++ b/bin/create-c-app
@@ -24,14 +24,14 @@ realpath_macos() {
   [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
 }
 
-# Silence a command:
+# Silence a command, exit if it fails:
 q_cmd() {
   "$@" >/dev/null 2>&1
   ret=$?
   if [ $ret -ne 0 ]; then
     echo "${FMT_RED}*** Error: Command '$*' failed${FMT_RESET}"
+    exit 1
   fi
-  return $ret
 }
 
 # Check if a provided directory exists, exit if it does not:
@@ -186,8 +186,8 @@ SETUP_PROJECT() {
     cp "$VSCODE_INIT_DIR/$VSCODE_TPL/"*.json "$PROJECT_DIR/.vscode/" || return 1
     cp "$VSCODE_INIT_DIR/workspace_settings/"*.json "$PROJECT_DIR/.vscode/" || return 1
     UPDATE_PROJECT_FILES || return 1
-    CHECK_OS_SPECIFICS || return 1
-    GIT_INIT_REPO || return 1
+    CHECK_OS_SPECIFICS
+    GIT_INIT_REPO
   else
     return 1
   fi
