Better error handling of project setup

diff --git a/bin/create-c-app b/bin/create-c-app
--- a/bin/create-c-app
+++ b/bin/create-c-app
@@ -29,7 +29,7 @@ q_cmd() {
   "$@" >/dev/null 2>&1
   ret=$?
   if [ $ret -ne 0 ]; then
-    echo "Error: Command '$*' failed"
+    echo "${FMT_RED}*** Error: Command '$*' failed${FMT_RESET}"
   fi
   return $ret
 }
@@ -152,8 +152,17 @@ GIT_INIT_REPO() {
 
 # Set project name in template files:
 UPDATE_PROJECT_FILES() {
-  find "$PROJECT_DIR" -type f -exec sed -i.bak "s/xxxxxxxxx/$APP/g" {} +
-  find "$PROJECT_DIR" -type f -name "*.bak" -exec rm -f {} +
+  if find "$PROJECT_DIR" -type f -exec sed -i.bak "s/xxxxxxxxx/$APP/g" {} +; then
+    if find "$PROJECT_DIR" -type f -name "*.bak" -exec rm -f {} +; then
+      return 0
+    else
+      echo "${FMT_RED}*** Error: Failed to remove backup files.${FMT_RESET}"
+      return 1
+    fi
+  else
+    echo "${FMT_RED}*** Error: Failed to update project files.${FMT_RESET}"
+    return 1
+  fi
 }
 
 # Adjustments based on OS:
@@ -170,14 +179,18 @@ CHECK_OS_SPECIFICS() {
 # Create a C project with vscode tasks in the provided directory:
 SETUP_PROJECT() {
   echo "${FMT_BOLD}*** Initializing $PROJECT_DESCRIPTION project '$APP' in $(dirname "$PROJECT_DIR")${FMT_RESET}"
-  mkdir -p "$PROJECT_DIR" &&
-  cp -r "$VSCODE_INIT_DIR/$TEMPLATE_DIR/." "$PROJECT_DIR/" &&
-  mkdir -p "$PROJECT_DIR/.vscode" &&
-  cp "$VSCODE_INIT_DIR/$VSCODE_TPL/"*.json "$PROJECT_DIR/.vscode/" &&
-  cp "$VSCODE_INIT_DIR/workspace_settings/"*.json "$PROJECT_DIR/.vscode/" &&
-  UPDATE_PROJECT_FILES &&
-  CHECK_OS_SPECIFICS &&
-  GIT_INIT_REPO
+
+  if mkdir -p "$PROJECT_DIR"; then
+    cp -r "$VSCODE_INIT_DIR/$TEMPLATE_DIR/." "$PROJECT_DIR/" || return 1
+    mkdir -p "$PROJECT_DIR/.vscode" || return 1
+    cp "$VSCODE_INIT_DIR/$VSCODE_TPL/"*.json "$PROJECT_DIR/.vscode/" || return 1
+    cp "$VSCODE_INIT_DIR/workspace_settings/"*.json "$PROJECT_DIR/.vscode/" || return 1
+    UPDATE_PROJECT_FILES || return 1
+    CHECK_OS_SPECIFICS || return 1
+    GIT_INIT_REPO || return 1
+  else
+    return 1
+  fi
 }
 
 # Start Visual Studio Code if it is installed:
@@ -197,7 +210,10 @@ START_VSCODE() {
 # Application start section:
 
 # Execute setup functions:
-SETUP_PROJECT
+SETUP_PROJECT || {
+  echo "${FMT_RED}*** Error: Failed to setup project $PROJECT_DIR${FMT_RESET}"
+  exit 1
+}
 START_VSCODE
 echo "${FMT_BOLD}${FMT_GREEN}*** Project created in:" "${FMT_WHITE}""$PROJECT_DIR${FMT_RESET}"
 
